cmake_policy(SET CMP0057 NEW)

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_DEPLOYMENT_TARGET "10.13")
set(VCPKG_BUILD_TYPE release)

if(DEFINED ENV{PKG_CONFIG_PATH})
    set(ENV{PKG_CONFIG_PATH} "${CMAKE_CURRENT_LIST_DIR}/macos_pkgconfig:$ENV{PKG_CONFIG_PATH}")
else()
    set(ENV{PKG_CONFIG_PATH} "${CMAKE_CURRENT_LIST_DIR}/macos_pkgconfig")
endif()

list(APPEND VCPKG_SYSTEM_LIBRARIES "z" "bz2")
set(OPENRCT2_SYSTEM_PACKAGES "zlib" "bzip2")
if(PORT IN_LIST OPENRCT2_SYSTEM_PACKAGES)
    set(CURRENT_PORT_DIR "${CMAKE_CURRENT_LIST_DIR}/dummy-port")
endif()
