set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_DEPLOYMENT_TARGET "10.13")

set(VCPKG_BUILD_TYPE release)

#if(PORT STREQUAL "zlib" OR PORT STREQUAL "bzip2")
#    set(CURRENT_PORT_DIR "../dummy-port")
#endif()
